<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Stopwords Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopwordsRepository extends EntityRepository
{

}
